🚧 chore: update

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -2,8 +2,8 @@
 deno run --allow-read --allow-env --allow-sys --allow-run npm:@commitlint/cli --edit "$1" --config .commitlintrc
 
 if [ $? -ne 0 ]; then
-    echo "Commit message validation failed. Please fix the issues and try again."
-    exit 1
+  echo "Commit message validation failed. Please fix the issues and try again."
+  exit 1
 fi
 
 echo "Commit message validation passed. Proceeding with commit."
diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -2,8 +2,8 @@
 deno task check
 
 if [ $? -ne 0 ]; then
-    echo "Pre-push hook failed. Please fix the issues and try again."
-    exit 1
+  echo "Pre-push hook failed. Please fix the issues and try again."
+  exit 1
 fi
 
 echo "Pre-push hook passed. Proceeding with push."
